# Service YAML for OpenJDK pod
apiVersion: v1
kind: Service
metadata:
  name: openjdk-service
spec:
  selector:
    app: openjdk-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
