apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: nginxapp-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: nginxapp
  template:  
    metadata: # Dictionary
      name: nginxapp-pod
      labels: # Dictionary
        app: nginxapp  # Key value pairs
    spec:
      containers: # List
        - name: nginxapp-container
          image: devnv/nginxweb1:latest
          ports: 
            - containerPort: 80  
      imagePullSecrets:
        - name: registrycred
    
